version: '1.0'
services:
  pcr-qr-healthcheck:
    image: pcr-qr-healthcheck:latest
    container_name: pcr-qr-healthcheck
    restart: unless-stopped
    network_mode: host
    command:
      - python3.10
      - main.py
    volumes:
      - ./app:/app
      - ./config:/config
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    logging:
      driver: none